name: Test Report
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
jobs:
  report:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Display test report
        uses: dorny/test-reporter@v1.6.0
        with:
          artifact: test-results
          name: JUnit Tests
          path: '**/*.xml'
          reporter: java-junit

      - name: Display Checkstyle report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          artifact: checkstyle-report
          path: '*.xml'
