name: CI
on:
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    name: test (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11' ]
    steps:
      - name: actions/setup-java@v3 (JDK ${{ matrix.java }})
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: x64
      - uses: actions/checkout@v3
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle test
        run: ./gradlew test

      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if the previous step failed
        with:
          name: test-results
          path: build/test-results/**/*.xml
